<?php

namespace Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Rubrique extends \Rubrique implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdrubrique()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idrubrique"];
        }
        $this->__load();
        return parent::getIdrubrique();
    }

    public function setNomrubrique($nomrubrique)
    {
        $this->__load();
        return parent::setNomrubrique($nomrubrique);
    }

    public function getNomrubrique()
    {
        $this->__load();
        return parent::getNomrubrique();
    }

    public function setDescriptionrubrique($descriptionrubrique)
    {
        $this->__load();
        return parent::setDescriptionrubrique($descriptionrubrique);
    }

    public function getDescriptionrubrique()
    {
        $this->__load();
        return parent::getDescriptionrubrique();
    }

    public function setIduser(\User $iduser = NULL)
    {
        $this->__load();
        return parent::setIduser($iduser);
    }

    public function getIduser()
    {
        $this->__load();
        return parent::getIduser();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idrubrique', 'nomrubrique', 'descriptionrubrique', 'iduser');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}